<script setup>
 
</script>

<template>
 <div class="navbar bg-base-100">
  <div class="flex-1">
    <a class="btn btn-ghost normal-case text-xl">Border Radius</a>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li><a>Item 1</a></li>
      <li tabindex="0">
        <a>
          Theme
          <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
        </a>
        <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="light" data-act-class="[&amp;_svg]:visible"><div data-theme="light" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">light</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left [&amp;_svg]:visible" data-set-theme="dark" data-act-class="[&amp;_svg]:visible"><div data-theme="dark" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">dark</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="cupcake" data-act-class="[&amp;_svg]:visible"><div data-theme="cupcake" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">cupcake</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="bumblebee" data-act-class="[&amp;_svg]:visible"><div data-theme="bumblebee" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">bumblebee</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="emerald" data-act-class="[&amp;_svg]:visible"><div data-theme="emerald" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">emerald</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="corporate" data-act-class="[&amp;_svg]:visible"><div data-theme="corporate" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">corporate</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="synthwave" data-act-class="[&amp;_svg]:visible"><div data-theme="synthwave" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">synthwave</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="retro" data-act-class="[&amp;_svg]:visible"><div data-theme="retro" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">retro</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="cyberpunk" data-act-class="[&amp;_svg]:visible"><div data-theme="cyberpunk" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">cyberpunk</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="valentine" data-act-class="[&amp;_svg]:visible"><div data-theme="valentine" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">valentine</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="halloween" data-act-class="[&amp;_svg]:visible"><div data-theme="halloween" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">halloween</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="garden" data-act-class="[&amp;_svg]:visible"><div data-theme="garden" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">garden</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="forest" data-act-class="[&amp;_svg]:visible"><div data-theme="forest" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">forest</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="aqua" data-act-class="[&amp;_svg]:visible"><div data-theme="aqua" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">aqua</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="lofi" data-act-class="[&amp;_svg]:visible"><div data-theme="lofi" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">lofi</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="pastel" data-act-class="[&amp;_svg]:visible"><div data-theme="pastel" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">pastel</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="fantasy" data-act-class="[&amp;_svg]:visible"><div data-theme="fantasy" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">fantasy</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="wireframe" data-act-class="[&amp;_svg]:visible"><div data-theme="wireframe" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">wireframe</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="black" data-act-class="[&amp;_svg]:visible"><div data-theme="black" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">black</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="luxury" data-act-class="[&amp;_svg]:visible"><div data-theme="luxury" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">luxury</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="dracula" data-act-class="[&amp;_svg]:visible"><div data-theme="dracula" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">dracula</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="cmyk" data-act-class="[&amp;_svg]:visible"><div data-theme="cmyk" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">cmyk</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="autumn" data-act-class="[&amp;_svg]:visible"><div data-theme="autumn" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">autumn</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="business" data-act-class="[&amp;_svg]:visible"><div data-theme="business" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">business</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="acid" data-act-class="[&amp;_svg]:visible"><div data-theme="acid" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">acid</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="lemonade" data-act-class="[&amp;_svg]:visible"><div data-theme="lemonade" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">lemonade</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="night" data-act-class="[&amp;_svg]:visible"><div data-theme="night" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">night</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="coffee" data-act-class="[&amp;_svg]:visible"><div data-theme="coffee" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">coffee</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
          <li class="h-18 mb-3">
          <button class="outline-base-content overflow-hidden rounded-lg text-left" data-set-theme="winter" data-act-class="[&amp;_svg]:visible"><div data-theme="winter" class="bg-base-100 text-base-content w-full cursor-pointer font-sans"><div class="grid grid-cols-5 grid-rows-3"><div class="col-span-5 row-span-3 row-start-1 flex gap-2 py-3 px-4 items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="w-3 h-3 invisible"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"></path></svg> <div class="flex-grow text-sm font-bold">winter</div> <div class="flex flex-shrink-0 flex-wrap gap-1 h-full"><div class="bg-primary w-2 rounded"></div> <div class="bg-secondary w-2 rounded"></div> <div class="bg-accent w-2 rounded"></div> <div class="bg-neutral w-2 rounded"></div></div></div></div></div></button>
          </li>
           <a class="outline-base-content overflow-hidden rounded-lg" href="/theme-generator/"><div class="hover:bg-neutral hover:text-neutral-content w-full cursor-pointer font-sans"><div class="flex gap-2 p-3"><svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 fill-current" viewBox="0 0 512 512"><path d="M96,208H48a16,16,0,0,1,0-32H96a16,16,0,0,1,0,32Z"></path><line x1="90.25" y1="90.25" x2="124.19" y2="124.19"></line><path d="M124.19,140.19a15.91,15.91,0,0,1-11.31-4.69L78.93,101.56a16,16,0,0,1,22.63-22.63l33.94,33.95a16,16,0,0,1-11.31,27.31Z"></path><path d="M192,112a16,16,0,0,1-16-16V48a16,16,0,0,1,32,0V96A16,16,0,0,1,192,112Z"></path><line x1="293.89" y1="90.25" x2="259.95" y2="124.19"></line><path d="M260,140.19a16,16,0,0,1-11.31-27.31l33.94-33.95a16,16,0,0,1,22.63,22.63L271.27,135.5A15.94,15.94,0,0,1,260,140.19Z"></path><line x1="124.19" y1="259.95" x2="90.25" y2="293.89"></line><path d="M90.25,309.89a16,16,0,0,1-11.32-27.31l33.95-33.94a16,16,0,0,1,22.62,22.63l-33.94,33.94A16,16,0,0,1,90.25,309.89Z"></path><path d="M219,151.83a26,26,0,0,0-36.77,0l-30.43,30.43a26,26,0,0,0,0,36.77L208.76,276a4,4,0,0,0,5.66,0L276,214.42a4,4,0,0,0,0-5.66Z"></path><path d="M472.31,405.11,304.24,237a4,4,0,0,0-5.66,0L237,298.58a4,4,0,0,0,0,5.66L405.12,472.31a26,26,0,0,0,36.76,0l30.43-30.43h0A26,26,0,0,0,472.31,405.11Z"></path></svg> <div class="flex-grow text-sm font-bold">Make your theme!</div></div></div></a>
        </ul>
      </li>
      <li><a>Item 3</a></li>
    </ul>
  </div>
</div>
</template>
<style scoped>
 
</style>